# Generated by Django 5.0.6 on 2025-02-25 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recepies',
            new_name='Recipes',
        ),
    ]
