# Generated by Django 5.0.6 on 2025-03-23 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0003_category_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='recipe_instructions',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
