# Generated by Django 5.0.6 on 2025-03-23 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0004_recipes_recipe_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='recipe_ingredients',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
