# Generated by Django 5.0.6 on 2025-04-05 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0005_recipes_recipe_ingredients'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
