# Generated by Django 5.0.6 on 2025-04-06 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0007_recipes_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipes',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
