# Generated by Django 5.0.6 on 2025-04-09 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0011_remove_order_product_order_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
