# Generated by Django 5.0.6 on 2025-04-12 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0013_remove_order_customer_id_remove_order_product_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipes',
            name='category',
        ),
        migrations.AddField(
            model_name='recipes',
            name='category',
            field=models.ManyToManyField(to='recipeapp.category'),
        ),
    ]
