# Generated by Django 5.0.6 on 2025-04-16 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0014_remove_recipes_category_recipes_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipes',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
